import type { Metadata } from "next";
import { Kanit } from "next/font/google";

import "./globals.css";
import Header from "@/components/Header/Header";
import SideBar from "@/components/SideBar/SideBar";

// const rubik = Ubuntu({
//   subsets: ["latin"],
//   weight: "400"
// });

const kanit = Kanit({
  subsets: ["latin"],
  weight: "400",
});

// Kanit

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={kanit.className}>
        <main>{children}</main>
      </body>
    </html>
  );
}
